apiVersion: v1
kind: Service
metadata:
    name: svc-pieshop
    labels:
        product: pieshop
spec:
    selector:
        app: app-pieshop
    type: LoadBalancer
    ports:
    - port: 80
    targetPort: 80
    protocol: TCP
    name: http
---
apiVersion: extension/v1beta1
kind: Deployment
metadata:
    name: dep-pieshop
spec:
    replicas: 1
    strategy:
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
        type: RollingUpdate
    template:
        metadata:
        labels:
            app: app-pieshop
        spec:
            containers:
                -image: bethanyspieshopregistry.azurecr.io/fastsa85bethanyspieshop_bethanyspieshop:latest
                imagePullPolicy: IfNotPresent
                name: pieshop
                resources: {}
                ports:
                    - containerPort:80
            imagePullSecrets:
                - name: regsecret