version: '3.5'

networks:
    local:
        name: local
        
services:  
    bethanyspieshop:
        build: BethanysPieShop/
        restart: always
        ports:
            - "80:80"
        networks:
            - local